name: DragonEggEnchanting
main: me.Bahamut.DragonEggEnchanting.DragonEggEnchantingPlugin
description: Enchant your items past their limitations with materials and levels!
version: 1.2.0
author: Bahamut
commands:
  upgrade:
    description: Consumes either an Block of Emerald or Dragon Egg along with their respective levels.
  up:
    description: Alias of 'upgrade' command.